# Customer Churn Prediction

## 02 - Data Cleaning & Preparation

This notebook prepares the dataset for exploratory analysis and machine learning.

Cleaning activities include:

- Correcting data types
- Handling missing values
- Creating business-relevant indicators
- Removing unnecessary variables

In [16]:
import pandas as pd

from pathlib import Path

BASE_DIR = Path().resolve().parent 

file_path = BASE_DIR / "data" / "raw" / "Telco-Customer-Churn.csv"

df = pd.read_csv(file_path)

df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

## Convert TotalCharges to Numeric

The `TotalCharges` column is currently stored as an object because it contains blank string values.

Converting this field to numeric format allows it to be used for analysis and machine learning.

In [19]:
df["TotalCharges"] = pd.to_numeric(
    df["TotalCharges"],
    errors="coerce"
)

In [20]:
df.isnull().sum()

customerID           0
gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

### Observation

Blank values have now been converted into proper missing values (`NaN`), making them easier to handle consistently.

## Handle Missing Values

Customers with missing `TotalCharges` all have zero tenure and therefore have not yet accumulated charges.

Replacing these values with 0 accurately reflects their business meaning.

In [22]:
df["TotalCharges"] = df["TotalCharges"].fillna(0)

In [23]:
df["TotalCharges"].isnull().sum()

np.int64(0)

## Create New Customer Indicator

Customers with zero tenure represent a unique customer segment and may behave differently from long-term customers.

A binary indicator is created to explicitly capture this information.

In [26]:
df["IsNewCustomer"] = (df["tenure"] == 0).astype(int)

df["IsNewCustomer"].value_counts()

IsNewCustomer
0    7032
1      11
Name: count, dtype: int64

## Remove Non-Predictive Features

The `customerID` column serves only as a unique identifier and does not contain information useful for prediction.

Removing it simplifies the dataset and prevents unnecessary noise during modeling.

In [28]:
df.drop("customerID", axis=1, inplace=True)

In [29]:
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,...,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,IsNewCustomer
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,...,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No,0
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,...,No,No,No,One year,No,Mailed check,56.95,1889.50,No,0
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,...,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,0
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,...,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No,0
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,...,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,0

## Final Validation

Before proceeding, we verify that the dataset contains no remaining missing values.

In [30]:
df.isnull().sum().sum()

np.int64(0)

### Validation Result

The dataset is now fully cleaned and contains no missing values.

## Save Cleaned Dataset

The cleaned dataset will be stored for downstream analysis and feature engineering.

In [31]:
output_path = BASE_DIR / "data" / "processed" / "cleaned_churn.csv"

df.to_csv(output_path, index=False)

print("Cleaned dataset saved successfully.")

Cleaned dataset saved successfully.

# Data Cleaning Summary

### Cleaning Actions Performed

- Converted `TotalCharges` to numeric format.
- Handled missing `TotalCharges` values.
- Created `IsNewCustomer`.
- Removed `customerID`.
- Verified dataset integrity.

### Result

The dataset is now analysis-ready and can be used for exploratory data analysis and feature engineering.

-   Next Notebook: 03_feature_engineering.ipynb